server:
  port: 8080
spring:
  application:
    name: mybatis-annotation

  datasource:
    url: jdbc:mysql://localhost:3306/annotation?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    ##配置项:开启下划线到驼峰的自动转换，作用:将数据库字段根据驼峰规则自动注入到对象属性
    map-underscore-to-camel-case: on
logging:
  level:
    com.wpw.mybatisannotation: debug